#!/usr/bin/env python3
"""scaffold-hugo.py — deterministic Hugo project scaffolder for a docs/ space.

Owned by the create-pages skill (mount mode). Stdlib-only; prints exactly one JSON
object to stdout per invocation.

docs/ is both the Hugo project root and the single content source: every content
path is *mounted* into Hugo (module mounts), never copied, so the Markdown tree
stays pure and no file is duplicated. Directory indexes stay `index.md` (project
naming convention) and are mounted as `_index.md` so Hugo reads each directory as
a branch bundle instead of a leaf bundle (which would demote sibling pages to
mere resources).

Actions:
  scaffold  write missing scaffold files and sync the managed mount block
  check     report drift without writing (missing files, stale mounts, collisions)
  mounts    print the computed mount block only
  build     run `hugo --minify` inside docs/ when the binary is available
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

MANAGED_BEGIN = "# >>> speckit:mounts"
MANAGED_END = "# <<< speckit:mounts"
MANAGED_NOTE = "generated by scaffold-hugo.py — re-run after adding a docs/ directory"

# Directories inside docs/ owned by the scaffold or by Hugo's build, never content.
SCAFFOLD_DIRS = ("layouts", "static", "public", "resources", "themes", "archetypes")
# Hugo component names that silently change meaning if a docs/ directory uses them.
HUGO_RESERVED = ("assets", "content", "data", "i18n", "config")

INDEX = "index.md"
CONFIG_NAME = "hugo.toml"
TEMPLATE_NAME = "hugo.toml.tmpl"
GITIGNORE_SOURCE = "dotgitignore"
GITIGNORE_TARGET = ".gitignore"


def assets_dir() -> Path:
    """${SKILL_HOME}/assets/hugo — resolved from this script's own location."""
    return Path(__file__).resolve().parents[1] / "assets" / "hugo"


def has_markdown(directory: Path) -> bool:
    return any(directory.rglob("*.md"))


def discover(docs: Path) -> dict:
    """Classify docs/ children and compute the index.md -> _index.md remaps."""
    content_dirs: list[str] = []
    media_dirs: list[str] = []
    collisions: list[dict] = []

    for child in sorted(docs.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if child.name in SCAFFOLD_DIRS:
            continue
        if child.name in HUGO_RESERVED:
            collisions.append({
                "path": f"{docs.name}/{child.name}",
                "detail": f"'{child.name}' is a Hugo component name; mounted explicitly, "
                          "but consider renaming the documentation directory",
            })
        (content_dirs if has_markdown(child) else media_dirs).append(child.name)

    remaps: list[tuple[str, str]] = []
    if (docs / INDEX).is_file():
        remaps.append((INDEX, "content/_index.md"))
    for name in content_dirs:
        for path in sorted((docs / name).rglob(INDEX)):
            rel = path.relative_to(docs).as_posix()
            parent = path.parent.relative_to(docs).as_posix()
            remaps.append((rel, f"content/{parent}/_index.md"))

    return {
        "content_dirs": content_dirs,
        "media_dirs": media_dirs,
        "index_remaps": [{"source": s, "target": t} for s, t in remaps],
        "reserved_collisions": collisions,
    }


def mounts_block(found: dict) -> str:
    """Render the managed mount block. Deterministic ordering."""
    remap_sources = {r["source"] for r in found["index_remaps"]}
    lines = [f"{MANAGED_BEGIN} — {MANAGED_NOTE}"]

    def mount(source: str, target: str, exclude: list[str] | None = None) -> None:
        lines.append("[[module.mounts]]")
        lines.append(f'  source = "{source}"')
        lines.append(f'  target = "{target}"')
        if exclude:
            rendered = ", ".join(f'"{pattern}"' for pattern in exclude)
            lines.append(f"  excludeFiles = [{rendered}]")
        lines.append("")

    # An explicit mount replaces Hugo's default mount for that component, so the
    # scaffold's own static/ directory must be re-declared alongside media mounts.
    mount("static", "static")
    for name in found["content_dirs"]:
        nested = any(source.startswith(f"{name}/") for source in remap_sources)
        mount(name, f"content/{name}", [INDEX, f"**/{INDEX}"] if nested else None)
        # Media stored beside Markdown must still be served at its repo-relative path.
        mount(name, f"static/{name}", ["*.md", "**/*.md"])
    for name in found["media_dirs"]:
        mount(name, f"static/{name}")
    for remap in found["index_remaps"]:
        mount(remap["source"], remap["target"])

    lines.append(MANAGED_END)
    return "\n".join(lines) + "\n"


def current_block(text: str) -> str | None:
    """The managed block exactly as it appears on disk. None when markers are absent."""
    start = text.find(MANAGED_BEGIN)
    if start == -1:
        return None
    end = text.find(MANAGED_END, start)
    if end == -1:
        return None
    return text[start:end + len(MANAGED_END)]


def asset_files() -> list[tuple[Path, str]]:
    """(source, docs-relative target) for every verbatim scaffold file."""
    base = assets_dir()
    pairs: list[tuple[Path, str]] = []
    for path in sorted(base.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(base).as_posix()
        if rel == TEMPLATE_NAME:
            continue
        pairs.append((path, GITIGNORE_TARGET if rel == GITIGNORE_SOURCE else rel))
    return pairs


def classify_write(target: Path, payload: str) -> str:
    if not target.exists():
        return "created"
    return "unchanged" if target.read_text(encoding="utf-8") == payload else "kept"


def render_config(site_title: str, description: str, block: str) -> str:
    template = (assets_dir() / TEMPLATE_NAME).read_text(encoding="utf-8")
    return (template
            .replace("{{SITE_TITLE}}", site_title)
            .replace("{{SITE_DESCRIPTION}}", description)
            .replace("{{MOUNTS}}", block))


def run(root: Path, docs_name: str, site_title: str, description: str,
        write: bool, force: bool) -> dict:
    docs = root / docs_name
    if not docs.is_dir():
        return {"error": f"docs directory not found: {docs_name}", "clean": False}

    found = discover(docs)
    block = mounts_block(found)
    files: list[dict] = []

    config_path = docs / CONFIG_NAME
    block_text = block.rstrip("\n")
    if not config_path.exists():
        payload = render_config(site_title, description, block_text)
        config_action = "created"
    else:
        current = config_path.read_text(encoding="utf-8")
        existing = current_block(current)
        if existing is None:
            payload, config_action = current, "unmanaged"
        elif existing == block_text:
            payload, config_action = current, "unchanged"
        else:
            payload = current.replace(existing, block_text, 1)
            config_action = "mounts-synced"
    if write and config_action in ("created", "mounts-synced"):
        config_path.write_text(payload, encoding="utf-8")
    files.append({"path": f"{docs_name}/{CONFIG_NAME}", "action": config_action})

    for source, rel in asset_files():
        target = docs / rel
        payload = source.read_text(encoding="utf-8")
        action = classify_write(target, payload)
        if action == "kept" and force:
            action = "overwritten"
        if write and action in ("created", "overwritten"):
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(payload, encoding="utf-8")
        files.append({"path": f"{docs_name}/{rel}", "action": action})

    pending = [f for f in files if f["action"] in ("created", "mounts-synced", "unmanaged")]
    kept = [f for f in files if f["action"] == "kept"]
    return {
        "docs_dir": docs_name,
        "dry_run": not write,
        "content_mounts": found["content_dirs"],
        "media_mounts": found["media_dirs"],
        "index_remaps": found["index_remaps"],
        "reserved_collisions": found["reserved_collisions"],
        "files": files,
        "kept_user_versions": [f["path"] for f in kept],
        "clean": not pending if not write else True,
        "hugo_available": shutil.which("hugo") is not None,
    }


def cmd_build(root: Path, docs_name: str, base_url: str | None) -> dict:
    docs = root / docs_name
    hugo = shutil.which("hugo")
    if hugo is None:
        return {
            "built": False,
            "reason": "hugo-not-installed",
            "guidance": "install Hugo extended (https://gohugo.io/installation/), "
                        f"then run: cd {docs_name} && hugo --minify",
            "clean": True,
        }
    if not (docs / CONFIG_NAME).is_file():
        return {"built": False, "reason": "not-scaffolded",
                "guidance": "run --action scaffold first", "clean": False}
    cmd = [hugo, "--minify"]
    if base_url:
        cmd += ["--baseURL", base_url]
    proc = subprocess.run(cmd, cwd=docs, capture_output=True, text=True)
    tail = [line for line in (proc.stdout or "").splitlines() if line.strip()][-12:]
    return {
        "built": proc.returncode == 0,
        "returncode": proc.returncode,
        "output_dir": f"{docs_name}/public",
        "stdout_tail": tail,
        "stderr_tail": [line for line in (proc.stderr or "").splitlines() if line.strip()][-12:],
        "clean": proc.returncode == 0,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Hugo scaffolder for the docs space")
    parser.add_argument("--action", required=True,
                        choices=["scaffold", "check", "mounts", "build"])
    parser.add_argument("--root", default=".", help="project root (SKILL_WORKDIR)")
    parser.add_argument("--docs-dir", default="docs", help="documentation directory name")
    parser.add_argument("--site-title", default=None)
    parser.add_argument("--description", default="Project documentation")
    parser.add_argument("--base-url", default=None, help="baseURL override for build")
    parser.add_argument("--force", action="store_true",
                        help="overwrite scaffold files the user has edited")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    site_title = args.site_title or root.name

    if args.action == "build":
        out = cmd_build(root, args.docs_dir, args.base_url)
    elif args.action == "mounts":
        docs = root / args.docs_dir
        out = ({"error": f"docs directory not found: {args.docs_dir}", "clean": False}
               if not docs.is_dir() else {"mounts": mounts_block(discover(docs)), "clean": True})
    else:
        out = run(root, args.docs_dir, site_title, args.description,
                  write=args.action == "scaffold", force=args.force)

    json.dump(out, sys.stdout, ensure_ascii=False, indent=2)
    sys.stdout.write("\n")
    return 0 if out.get("clean", True) else 1


if __name__ == "__main__":
    sys.exit(main())
