#!/usr/bin/env python3
"""scaffold-hugo.py — deterministic Hugo project scaffolder for a docs/ space.

Owned by the create-pages skill (mount mode). Stdlib-only; prints exactly one JSON
object to stdout per invocation.

docs/ is both the Hugo project root and the single content source: every content
path is *mounted* into Hugo (module mounts), never copied, so the Markdown tree
stays pure and no file is duplicated. Directory indexes stay `index.md` (project
naming convention) and are mounted as `_index.md` so Hugo reads each directory as
a branch bundle instead of a leaf bundle (which would demote sibling pages to
mere resources).

Rendering runs in one of two modes. `book` uses the preferred theme — Hugo Book
(alex-shpak/hugo-book), vendored under docs/themes/book — and completes the site
navigation from the live docs tree: reading order, labels and collapse come from a
managed cascade in hugo.toml, and every directory without an index.md gets a section
landing page by mounting one shared stub. `builtin` is the self-contained fallback
layout set, used when the theme is not installed. Neither mode writes documentation.

Actions:
  scaffold  write missing scaffold files and sync the managed navigation+mount block
  check     report drift without writing (missing files, stale mounts, collisions)
  mounts    print the computed navigation+mount block only
  build     run `hugo --minify` in the CI image (docker), or locally as a fallback
  theme     report the vendored theme's state; with --fetch, install/update it
  image     print the docker image a build would use, and where it came from
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

MANAGED_BEGIN = "# >>> speckit:mounts"
MANAGED_END = "# <<< speckit:mounts"
MANAGED_NOTE = "generated by scaffold-hugo.py — navigation + mounts; re-run after " \
               "adding a docs/ directory"

# Directories inside docs/ owned by the scaffold or by Hugo's build, never content.
SCAFFOLD_DIRS = ("layouts", "static", "public", "resources", "themes", "archetypes")
# Hugo component names that silently change meaning if a docs/ directory uses them.
HUGO_RESERVED = ("assets", "content", "data", "i18n", "config")

INDEX = "index.md"
CONFIG_NAME = "hugo.toml"
TEMPLATE_NAME = "hugo.toml.tmpl"
# Asset paths that cannot be stored dot-prefixed inside the skill package.
ASSET_RENAMES = {
    "dotgitignore": ".gitignore",
    "dotspeckit/nav/section-index.md": ".speckit/nav/section-index.md",
}
# The one shared stub mounted as the section index of every directory lacking index.md.
NAV_STUB = ASSET_RENAMES["dotspeckit/nav/section-index.md"]

# Preferred theme, and the marker that identifies a config rendered for it.
THEME_MODES = ("auto", "book", "builtin")
THEME_DIR = "themes/book"
THEME_MARKER = 'theme = "book"'
THEME_URL = "https://github.com/alex-shpak/hugo-book.git"
THEME_REF = "v0.14.0"
THEME_MIN_HUGO = "0.158.0"
# Runtime parts of the theme. Everything else it ships (example site, screenshots,
# archetypes, readme, git metadata) is dropped, so no third-party Markdown lands in
# the docs space where the documentation validator would audit it.
THEME_KEEP = ("layouts", "assets", "static", "i18n", "theme.toml", "hugo.toml", "LICENSE")
PROVENANCE = ".speckit-theme.json"

# Canonical reading order of the documentation taxonomy; other directories follow in
# alphabetical order. Drives the sidebar, which otherwise sorts alphabetically and
# opens with `archive/`.
TYPE_ORDER = ("concepts", "tutorials", "tasks", "reference", "decisions", "contribute",
              "notes", "archive")
# Directory names that are acronyms, for labelling generated section indexes.
ACRONYMS = {"adr": "ADR", "ai": "AI", "api": "API", "cd": "CD", "ci": "CI", "cli": "CLI",
            "cpu": "CPU", "faq": "FAQ", "gpu": "GPU", "http": "HTTP", "io": "IO",
            "mcp": "MCP", "os": "OS", "sdk": "SDK", "sql": "SQL", "ui": "UI",
            "ux": "UX", "vm": "VM"}
COLLAPSE_THRESHOLD = 6

# Builds run in the CI image by default, so a local render and the CI render use the
# same Hugo: a workstation binary is usually older than the image (and often older than
# the theme's minimum), which makes "works locally" mean nothing.
RUNNERS = ("auto", "docker", "local")
IMAGE_ENV = "SPECKIT_HUGO_IMAGE"
IMAGE_FILE = "hugo-image.txt"          # shared with scaffold-ci.sh (stage 3)
IMAGE_FALLBACK = "reg.docker.alibaba-inc.com/xuanji-images/hugo:latest"
# Rendered pipelines to read the image from, so the local build follows a project that
# overrode it. Ordered: first match wins.
CI_FILES = (".aoneci/deploy-pages.yaml", ".github/workflows/deploy-pages.yaml")
WORKDIR = "/workspace"


def registry_image() -> str:
    """The shared default image: first non-comment line of ci-templates/hugo-image.txt."""
    path = Path(__file__).resolve().parent / "ci-templates" / IMAGE_FILE
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            entry = line.strip()
            if entry and not entry.startswith("#"):
                return entry
    return IMAGE_FALLBACK


def ci_image(root: Path) -> str | None:
    """The image a rendered CI pipeline actually uses — the strongest 'same as CI' signal."""
    for rel in CI_FILES:
        path = root / rel
        if not path.is_file():
            continue
        found = re.search(r"^\s*image:\s*(\S+)\s*$", path.read_text(encoding="utf-8"), re.M)
        if found:
            return found.group(1).strip("'\"")
    return None


def resolve_image(root: Path, override: str | None) -> dict:
    """Explicit flag > environment > rendered CI pipeline > shared registry default."""
    if override:
        return {"image": override, "image_source": "flag"}
    from_env = os.environ.get(IMAGE_ENV)
    if from_env:
        return {"image": from_env, "image_source": f"env:{IMAGE_ENV}"}
    from_ci = ci_image(root)
    if from_ci:
        return {"image": from_ci, "image_source": "ci-pipeline"}
    return {"image": registry_image(), "image_source": "ci-templates/" + IMAGE_FILE}


def assets_dir(mode: str) -> Path:
    """${SKILL_HOME}/assets/<mode> — resolved from this script's own location."""
    folder = "book" if mode == "book" else "hugo"
    return Path(__file__).resolve().parents[1] / "assets" / folder


def has_markdown(directory: Path) -> bool:
    return any(directory.rglob("*.md"))


def version_tuple(text: str) -> tuple:
    return tuple(int(part) for part in text.split(".")[:3])


def hugo_version() -> str | None:
    """The installed Hugo's version, or None when the binary is absent/unreadable."""
    hugo = shutil.which("hugo")
    if hugo is None:
        return None
    proc = subprocess.run([hugo, "version"], capture_output=True, text=True)
    found = re.search(r"v(\d+\.\d+\.\d+)", proc.stdout)
    return found.group(1) if found else None


def theme_state(docs: Path, request: str) -> dict:
    """Which mode this run renders in, and everything known about the vendored theme.

    `auto` prefers the theme and degrades to the built-in layouts when it is absent;
    an explicit `book` request never degrades (the caller decides what to do).
    `config_mode` is what the site on disk actually selects, which is what a build has
    to respect — a vendored theme means nothing while hugo.toml renders builtin.
    """
    theme_root = docs / THEME_DIR
    present = (theme_root / "theme.toml").is_file()
    min_hugo = THEME_MIN_HUGO
    if present:
        # theme.toml's min_version is the author's declared floor; Hugo enforces the
        # same number through the theme's own hugo.toml (module.hugoVersion.min).
        declared = re.search(r'min_version\s*=\s*"([\d.]+)"',
                             (theme_root / "theme.toml").read_text(encoding="utf-8"))
        if declared:
            min_hugo = declared.group(1)
    record = {}
    provenance = theme_root / PROVENANCE
    if provenance.is_file():
        try:
            record = json.loads(provenance.read_text(encoding="utf-8"))
        except ValueError:
            record = {}
    config = docs / CONFIG_NAME
    config_mode = None
    if config.is_file():
        config_mode = "book" if THEME_MARKER in config.read_text(encoding="utf-8") \
            else "builtin"
    installed = hugo_version()
    mode = "book" if (request == "book" or (request == "auto" and present)) else "builtin"
    state = {
        "request": request,
        "mode": mode,
        "config_mode": config_mode,
        "present": present,
        "dir": f"{docs.name}/{THEME_DIR}",
        "ref": record.get("ref"),
        "commit": record.get("commit"),
        "url": record.get("url"),
        "min_hugo": min_hugo,
        "hugo_version": installed,
        "compatible": None,
        "vendored_markdown": len(list((docs / "themes").rglob("*.md")))
        if (docs / "themes").is_dir() else 0,
    }
    # The floor only binds a site that actually uses the theme.
    if (config_mode or mode) == "book" and installed is not None:
        state["compatible"] = version_tuple(installed) >= version_tuple(min_hugo)
    return state


def section_dirs(docs: Path, top: str) -> list[str]:
    """docs-relative paths of every directory at or below a content mount that holds
    Markdown — exactly the directories Hugo has to read as sections."""
    found = [top]
    for path in sorted((docs / top).rglob("*")):
        if not path.is_dir():
            continue
        rel = path.relative_to(docs)
        if any(part.startswith(".") for part in rel.parts):
            continue
        if has_markdown(path):
            found.append(rel.as_posix())
    return found


def section_label(rel: str) -> str:
    """Label for a generated section index: it has no index.md to read an H1 from."""
    words = [w for w in rel.rsplit("/", 1)[-1].replace("_", "-").split("-") if w]
    return " ".join(ACRONYMS.get(w.lower(), w[:1].upper() + w[1:]) for w in words)


def discover(docs: Path, threshold: int = COLLAPSE_THRESHOLD) -> dict:
    """Classify docs/ children, compute the index.md -> _index.md remaps, and derive
    the section tree the navigation is built from."""
    content_dirs: list[str] = []
    media_dirs: list[str] = []
    collisions: list[dict] = []

    for child in sorted(docs.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if child.name in SCAFFOLD_DIRS:
            continue
        if child.name in HUGO_RESERVED:
            collisions.append({
                "path": f"{docs.name}/{child.name}",
                "detail": f"'{child.name}' is a Hugo component name; mounted explicitly, "
                          "but consider renaming the documentation directory",
            })
        (content_dirs if has_markdown(child) else media_dirs).append(child.name)

    remaps: list[tuple[str, str]] = []
    if (docs / INDEX).is_file():
        remaps.append((INDEX, "content/_index.md"))
    for name in content_dirs:
        for path in sorted((docs / name).rglob(INDEX)):
            rel = path.relative_to(docs).as_posix()
            parent = path.parent.relative_to(docs).as_posix()
            remaps.append((rel, f"content/{parent}/_index.md"))

    # Reading order: the canonical taxonomy first, then anything else alphabetically.
    ordered = [name for name in TYPE_ORDER if name in content_dirs]
    ordered += [name for name in content_dirs if name not in TYPE_ORDER]
    weights = {name: (index + 1) * 10 for index, name in enumerate(ordered)}

    sections: list[dict] = []
    for rel in ["."] + [d for name in content_dirs for d in section_dirs(docs, name)]:
        directory = docs if rel == "." else docs / rel
        pages = [p for p in directory.rglob("*.md") if p.name != INDEX]
        sections.append({
            "path": rel,
            "has_index": (directory / INDEX).is_file(),
            "pages": len(pages),
            "weight": weights.get(rel),
            "collapse": rel != "." and len(pages) >= threshold,
        })

    return {
        "content_dirs": content_dirs,
        "media_dirs": media_dirs,
        "index_remaps": [{"source": s, "target": t} for s, t in remaps],
        "reserved_collisions": collisions,
        "sections": sections,
    }


def nav_lines(found: dict) -> list[str]:
    """Cascade entries that complete the sidebar without touching a single document:
    reading order for the taxonomy, a label for every generated section index, and
    collapse for crowded sections. Pages in a section are *not* matched, so a cascade
    never turns a document into a collapsible group."""
    lines: list[str] = []
    for section in found["sections"]:
        rel = section["path"]
        if rel == ".":   # the home page needs no order, label or toggle
            continue
        title = None if section["has_index"] else section_label(rel)
        if section["weight"] is None and title is None and not section["collapse"]:
            continue
        lines.append("[[cascade]]")
        if title is not None:
            lines.append(f'  title = "{title}"')
        if section["weight"] is not None:
            lines.append(f"  weight = {section['weight']}")
        if section["collapse"]:
            lines.append("  [cascade.params]")
            lines.append("    bookCollapseSection = true")
        lines.append("  [cascade.target]")
        lines.append(f'    path = "/{rel}"')
        lines.append("")
    return lines


def mounts_block(found: dict, book: bool = False) -> str:
    """Render the managed navigation+mount block. Deterministic ordering."""
    remap_sources = {r["source"] for r in found["index_remaps"]}
    lines = [f"{MANAGED_BEGIN} — {MANAGED_NOTE}"]

    def mount(source: str, target: str, exclude: list[str] | None = None) -> None:
        lines.append("[[module.mounts]]")
        lines.append(f'  source = "{source}"')
        lines.append(f'  target = "{target}"')
        if exclude:
            rendered = ", ".join(f'"{pattern}"' for pattern in exclude)
            lines.append(f"  excludeFiles = [{rendered}]")
        lines.append("")

    if book:
        nav = nav_lines(found)
        if nav:
            lines.append("# navigation: reading order, generated labels, collapse")
            lines.extend(nav)

    # An explicit mount replaces Hugo's default mount for that component, so the
    # scaffold's own static/ directory must be re-declared alongside media mounts.
    mount("static", "static")
    for name in found["content_dirs"]:
        nested = any(source.startswith(f"{name}/") for source in remap_sources)
        mount(name, f"content/{name}", [INDEX, f"**/{INDEX}"] if nested else None)
        # Media stored beside Markdown must still be served at its repo-relative path.
        mount(name, f"static/{name}", ["*.md", "**/*.md"])
    for name in found["media_dirs"]:
        mount(name, f"static/{name}")
    for remap in found["index_remaps"]:
        mount(remap["source"], remap["target"])

    if book:
        # A nested directory without an _index.md is not a section at all: Hugo
        # attaches its pages to the nearest ancestor, so the sidebar loses the whole
        # grouping. One shared stub, mounted per directory, restores it.
        gaps = [s["path"] for s in found["sections"] if not s["has_index"]]
        if gaps:
            lines.append("# generated section indexes (directories without an index.md)")
        for rel in gaps:
            target = "content/_index.md" if rel == "." else f"content/{rel}/_index.md"
            mount(NAV_STUB, target)

    lines.append(MANAGED_END)
    return "\n".join(lines) + "\n"


def current_block(text: str) -> str | None:
    """The managed block exactly as it appears on disk. None when markers are absent."""
    start = text.find(MANAGED_BEGIN)
    if start == -1:
        return None
    end = text.find(MANAGED_END, start)
    if end == -1:
        return None
    return text[start:end + len(MANAGED_END)]


def asset_files(mode: str) -> list[tuple[Path, str]]:
    """(source, docs-relative target) for every verbatim scaffold file of a mode."""
    base = assets_dir(mode)
    pairs: list[tuple[Path, str]] = []
    for path in sorted(base.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(base).as_posix()
        if rel == TEMPLATE_NAME:
            continue
        pairs.append((path, ASSET_RENAMES.get(rel, rel)))
    return pairs


def prune_empty(directory: Path, stop: Path) -> None:
    """Drop directories left empty by a removed scaffold file, never past `stop`."""
    while directory != stop and directory.is_dir() and not any(directory.iterdir()):
        directory.rmdir()
        directory = directory.parent


def classify_write(target: Path, payload: str) -> str:
    if not target.exists():
        return "created"
    return "unchanged" if target.read_text(encoding="utf-8") == payload else "kept"


def render_config(mode: str, site_title: str, description: str, block: str) -> str:
    template = (assets_dir(mode) / TEMPLATE_NAME).read_text(encoding="utf-8")
    return (template
            .replace("{{SITE_TITLE}}", site_title)
            .replace("{{SITE_DESCRIPTION}}", description)
            .replace("{{MOUNTS}}", block))


def run(root: Path, docs_name: str, site_title: str, description: str,
        write: bool, force: bool, theme_request: str = "auto",
        threshold: int = COLLAPSE_THRESHOLD) -> dict:
    docs = root / docs_name
    if not docs.is_dir():
        return {"error": f"docs directory not found: {docs_name}", "clean": False}

    theme = theme_state(docs, theme_request)
    if theme_request == "book" and not theme["present"]:
        return {
            "error": f"Book theme requested but not installed at {theme['dir']}",
            "guidance": "install it with --action theme --fetch, or scaffold the "
                        "self-contained layouts with --theme builtin",
            "theme": theme,
            "clean": False,
        }
    mode = theme["mode"]
    book = mode == "book"

    found = discover(docs, threshold)
    block = mounts_block(found, book)
    files: list[dict] = []

    config_path = docs / CONFIG_NAME
    block_text = block.rstrip("\n")
    if not config_path.exists():
        payload = render_config(mode, site_title, description, block_text)
        config_action = "created"
    else:
        current = config_path.read_text(encoding="utf-8")
        if (THEME_MARKER in current) != book:
            # The config was rendered for the other mode, and the parts that differ
            # (theme line, theme params) sit outside the managed block: only a full
            # re-render switches modes, so it needs explicit consent.
            payload = render_config(mode, site_title, description, block_text)
            config_action = "rewritten" if force else "mode-mismatch"
        else:
            existing = current_block(current)
            if existing is None:
                payload, config_action = current, "unmanaged"
            elif existing == block_text:
                payload, config_action = current, "unchanged"
            else:
                payload = current.replace(existing, block_text, 1)
                config_action = "mounts-synced"
    if write and config_action in ("created", "mounts-synced", "rewritten"):
        config_path.write_text(payload, encoding="utf-8")
    files.append({"path": f"{docs_name}/{CONFIG_NAME}", "action": config_action})

    # A mode switch cannot be done piecemeal: dropping the other mode's layouts while
    # the config still selects them leaves an unbuildable site. So when the config is
    # blocked, the rest of this run only reports what a switch would do.
    if config_action == "mode-mismatch":
        write = False

    for source, rel in asset_files(mode):
        target = docs / rel
        payload = source.read_text(encoding="utf-8")
        action = classify_write(target, payload)
        if action == "kept" and force:
            action = "overwritten"
        if write and action in ("created", "overwritten"):
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(payload, encoding="utf-8")
        files.append({"path": f"{docs_name}/{rel}", "action": action})

    # A mode switch must not leave the other mode's files behind: a stray
    # layouts/_default/baseof.html silently replaces the theme's entire page shell.
    # Untouched scaffold files are removable (they come back on demand); edited ones
    # are reported for a human decision.
    own = {rel for _, rel in asset_files(mode)}
    for source, rel in asset_files("builtin" if book else "book"):
        target = docs / rel
        if rel in own or not target.exists():
            continue
        if target.read_bytes() == source.read_bytes():
            action = "removed"
            if write:
                target.unlink()
                prune_empty(target.parent, docs)
        else:
            action = "stale-edited"
        files.append({"path": f"{docs_name}/{rel}", "action": action})

    needs_decision = ("unmanaged", "mode-mismatch", "stale-edited")
    pending = [f for f in files
               if f["action"] in needs_decision + ("created", "mounts-synced", "removed")]
    unresolved = [f for f in files if f["action"] in needs_decision]
    kept = [f for f in files if f["action"] == "kept"]
    result = {
        "docs_dir": docs_name,
        "dry_run": not write,
        "theme": theme,
        "nav": {
            "applied": book,
            "sections": [s["path"] for s in found["sections"]],
            "generated_indexes": [s["path"] for s in found["sections"]
                                  if not s["has_index"]],
            "collapsed": [s["path"] for s in found["sections"] if s["collapse"]],
            "order": {s["path"]: s["weight"] for s in found["sections"] if s["weight"]},
        },
        "content_mounts": found["content_dirs"],
        "media_mounts": found["media_dirs"],
        "index_remaps": found["index_remaps"],
        "reserved_collisions": found["reserved_collisions"],
        "files": files,
        "kept_user_versions": [f["path"] for f in kept],
        "clean": not unresolved if write else not pending,
        "hugo_available": shutil.which("hugo") is not None,
    }
    if config_action == "mode-mismatch":
        result["guidance"] = (
            f"{docs_name}/{CONFIG_NAME} was rendered for the "
            f"{'builtin' if book else 'book'} mode; nothing was written. Re-run with "
            "--force to re-render it for this mode (customizations outside the managed "
            "block are lost), or keep the current mode with "
            f"--theme {'builtin' if book else 'book'}.")
    stale = [f["path"] for f in files if f["action"] == "stale-edited"]
    if stale:
        # Files of the other mode that carry local edits: this run neither keeps them
        # working nor throws the edits away.
        result["stale_edited"] = stale
    return result


def cmd_theme(docs: Path, ref: str, url: str, fetch: bool, force: bool) -> dict:
    """Report — and on request install — the vendored Hugo Book theme.

    The only action in this script that touches the network, kept apart from
    `scaffold` so rendering stays offline and deterministic. What lands on disk is a
    plain snapshot of the theme's runtime parts (no .git, no example site, no
    third-party Markdown), so it is committed with the project and CI needs neither
    network access nor Go.
    """
    if not docs.is_dir():
        return {"error": f"docs directory not found: {docs.name}", "clean": False}
    theme_root = docs / THEME_DIR
    state = theme_state(docs, "auto")
    state["fetched"] = False
    if not fetch:
        state["clean"] = True
        state["guidance"] = ("install or update with: --action theme --fetch "
                             f"[--theme-ref {ref}] [--theme-url <mirror>]"
                             if not state["present"] else
                             "installed; re-fetch with --action theme --fetch --force")
        return state

    git = shutil.which("git")
    if git is None:
        return {**state, "reason": "git-not-installed", "clean": False,
                "guidance": "install git, or unpack the theme manually into "
                            f"{state['dir']} (keep {', '.join(THEME_KEEP)})"}
    if theme_root.exists():
        if (theme_root / ".git").exists():
            return {**state, "reason": "managed-by-git", "clean": False,
                    "guidance": f"{state['dir']} carries its own .git (submodule or "
                                "clone): update it with git, not with this script"}
        if not force:
            return {**state,
                    "reason": "already-installed" if state["present"] else "unexpected-content",
                    "clean": state["present"],
                    "guidance": "pass --force to replace the vendored snapshot"
                    if state["present"] else
                    f"{state['dir']} exists but is not a theme: inspect it, then remove "
                    "it or pass --force to replace it"}
        shutil.rmtree(theme_root)

    theme_root.parent.mkdir(parents=True, exist_ok=True)
    clone = subprocess.run(
        [git, "-c", "advice.detachedHead=false", "clone", "--depth", "1",
         "--branch", ref, url, str(theme_root)],
        capture_output=True, text=True)
    if clone.returncode != 0:
        if theme_root.is_dir() and not (theme_root / "theme.toml").is_file():
            shutil.rmtree(theme_root, ignore_errors=True)
        return {**state, "reason": "clone-failed", "clean": False,
                "stderr_tail": [ln for ln in clone.stderr.splitlines() if ln.strip()][-6:],
                "guidance": "no network or unknown ref: retry with --theme-url <mirror>, "
                            "or scaffold with --theme builtin for now"}
    revision = subprocess.run([git, "-C", str(theme_root), "rev-parse", "HEAD"],
                              capture_output=True, text=True).stdout.strip()
    dropped = []
    for child in sorted(theme_root.iterdir()):
        if child.name in THEME_KEEP:
            continue
        dropped.append(child.name)
        shutil.rmtree(child) if child.is_dir() else child.unlink()
    (theme_root / PROVENANCE).write_text(
        json.dumps({"url": url, "ref": ref, "commit": revision,
                    "kept": list(THEME_KEEP), "dropped": dropped,
                    "installed_by": "create-pages scaffold-hugo.py --action theme"},
                   ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {**theme_state(docs, "auto"), "fetched": True, "dropped": dropped,
            "clean": True,
            "guidance": "commit the vendored theme so CI builds without network access, "
                        "then re-run --action scaffold"}


def hugo_command(base_url: str | None) -> str:
    """The one build command, identical in every runner and in the CI pipeline."""
    command = "hugo --minify"
    if base_url:
        command += f" --baseURL {base_url}"
    return command


def tail(text: str, lines: int = 12) -> list:
    return [line for line in (text or "").splitlines() if line.strip()][-lines:]


def build_in_docker(root: Path, docs_name: str, image: str, base_url: str | None) -> dict:
    """Run the build inside the CI image, so local output matches CI byte for byte.

    The workspace is bind-mounted, which writes `<docs>/public` straight back to the
    host. Some sandboxed daemons cannot see host paths; that is detected with a probe
    and reported rather than silently producing an empty site.
    """
    docker = shutil.which("docker")
    if docker is None:
        return {"built": False, "reason": "docker-not-installed"}
    mount = f"{root}:{WORKDIR}"
    probe = subprocess.run(
        [docker, "run", "--rm", "-v", mount, image,
         "sh", "-c", f"test -f {WORKDIR}/{docs_name}/{CONFIG_NAME}"],
        capture_output=True, text=True)
    if probe.returncode != 0:
        return {"built": False,
                "reason": "image-unavailable" if "Unable to find image" in probe.stderr
                          or "pull access denied" in probe.stderr
                          or "not found" in probe.stderr.lower() else "workspace-not-visible",
                "stderr_tail": tail(probe.stderr, 6)}
    command = hugo_command(base_url)
    proc = subprocess.run(
        [docker, "run", "--rm", "-v", mount, "-w", f"{WORKDIR}/{docs_name}", image,
         "sh", "-c", f"hugo version && {command}"],
        capture_output=True, text=True)
    version = re.search(r"hugo v(\d+\.\d+\.\d+)", proc.stdout or "")
    return {
        "built": proc.returncode == 0,
        "returncode": proc.returncode,
        "hugo_version": version.group(1) if version else None,
        "command": command,
        "stdout_tail": tail(proc.stdout),
        "stderr_tail": tail(proc.stderr),
    }


def build_locally(root: Path, docs_name: str, base_url: str | None, theme: dict) -> dict:
    hugo = shutil.which("hugo")
    if hugo is None:
        return {"built": False, "reason": "hugo-not-installed"}
    if theme.get("compatible") is False:
        # The theme enforces its own minimum, so this build would fail with a Hugo
        # error rather than a broken site.
        return {"built": False, "reason": "hugo-older-than-theme",
                "hugo_version": theme.get("hugo_version")}
    cmd = [hugo, "--minify"]
    if base_url:
        cmd += ["--baseURL", base_url]
    proc = subprocess.run(cmd, cwd=root / docs_name, capture_output=True, text=True)
    return {
        "built": proc.returncode == 0,
        "returncode": proc.returncode,
        "hugo_version": theme.get("hugo_version"),
        "command": hugo_command(base_url),
        "stdout_tail": tail(proc.stdout),
        "stderr_tail": tail(proc.stderr),
    }


def cmd_build(root: Path, docs_name: str, base_url: str | None,
              theme_request: str = "auto", runner: str = "auto",
              image_override: str | None = None) -> dict:
    docs = root / docs_name
    if not (docs / CONFIG_NAME).is_file():
        return {"built": False, "reason": "not-scaffolded",
                "guidance": "run --action scaffold first", "clean": False}
    theme = theme_state(docs, theme_request) if docs.is_dir() else {"compatible": None}
    resolved = resolve_image(root, image_override)
    result = {"docs_dir": docs_name, "output_dir": f"{docs_name}/public", "theme": theme,
              **resolved}

    attempts: list[dict] = []
    if runner in ("auto", "docker"):
        attempt = build_in_docker(root, docs_name, resolved["image"], base_url)
        attempts.append({"runner": "docker", **attempt})
        if attempt["built"] or runner == "docker":
            return {**result, **attempt, "runner": "docker", "attempts": attempts,
                    "clean": attempt["built"],
                    **({} if attempt["built"] else
                       {"guidance": docker_guidance(attempt, resolved["image"], docs_name)})}
    if runner in ("auto", "local"):
        attempt = build_locally(root, docs_name, base_url, theme)
        attempts.append({"runner": "local", **attempt})
        if attempt["built"]:
            return {**result, **attempt, "runner": "local", "attempts": attempts,
                    "clean": True,
                    "warning": "built with the local Hugo, not the CI image: the rendered "
                               "site may differ from CI"}
        # Neither runner produced a site. An environment gap (no docker, no binary, a
        # binary older than the theme) is not scaffold drift, so it stays `clean`.
        gap = attempt["reason"] in ("hugo-not-installed", "hugo-older-than-theme")
        return {**result, **attempt, "runner": "local", "attempts": attempts,
                "clean": gap,
                "guidance": local_guidance(attempt, theme, resolved["image"], docs_name)}
    return {**result, "built": False, "reason": f"unknown runner: {runner}", "clean": False}


def docker_guidance(attempt: dict, image: str, docs_name: str) -> str:
    reason = attempt.get("reason")
    if reason == "docker-not-installed":
        return ("docker is required to build with the CI image; install it, or accept a "
                "local-Hugo build with --runner local (version may differ from CI)")
    if reason == "image-unavailable":
        return (f"cannot pull {image}: it is environment-specific. Pass --hugo-image "
                f"<ref>, set {IMAGE_ENV}, or edit ci-templates/{IMAGE_FILE} so stage 3 "
                "renders the same image")
    if reason == "workspace-not-visible":
        return ("the docker daemon cannot see the host workspace (sandboxed daemon): copy "
                f"the tree into a container instead, or use --runner local")
    return f"build failed inside {image}; run: cd {docs_name} && {attempt.get('command')}"


def local_guidance(attempt: dict, theme: dict, image: str, docs_name: str) -> str:
    reason = attempt.get("reason")
    if reason == "hugo-older-than-theme":
        return (f"local Hugo {theme.get('hugo_version')} < {theme.get('min_hugo')} required "
                f"by the Book theme — build in the CI image ({image}, the default runner), "
                "upgrade Hugo, or scaffold with --theme builtin")
    if reason == "hugo-not-installed":
        return (f"no local Hugo and no usable docker image: install Hugo extended "
                f"(https://gohugo.io/installation/) or make {image} pullable, "
                f"then run: cd {docs_name} && hugo --minify")
    return f"local build failed; run it directly for full output: cd {docs_name} && hugo --minify"


def main() -> int:
    parser = argparse.ArgumentParser(description="Hugo scaffolder for the docs space")
    parser.add_argument("--action", required=True,
                        choices=["scaffold", "check", "mounts", "build", "theme", "image"])
    parser.add_argument("--root", default=".", help="project root (SKILL_WORKDIR)")
    parser.add_argument("--docs-dir", default="docs", help="documentation directory name")
    parser.add_argument("--site-title", default=None)
    parser.add_argument("--description", default="Project documentation")
    parser.add_argument("--base-url", default=None, help="baseURL override for build")
    parser.add_argument("--runner", default="auto", choices=list(RUNNERS),
                        help="build runner: auto (docker CI image, then local), docker, local")
    parser.add_argument("--hugo-image", default=None,
                        help=f"docker image for the build (default: {IMAGE_ENV} env, the "
                             f"rendered CI pipeline, or ci-templates/{IMAGE_FILE})")
    parser.add_argument("--theme", default="auto", choices=list(THEME_MODES),
                        help="auto: prefer the vendored Book theme, else built-in layouts")
    parser.add_argument("--theme-ref", default=THEME_REF,
                        help=f"theme git ref to install (default {THEME_REF})")
    parser.add_argument("--theme-url", default=THEME_URL, help="theme git URL or mirror")
    parser.add_argument("--fetch", action="store_true",
                        help="with --action theme: install/update the theme (network)")
    parser.add_argument("--collapse-threshold", type=int, default=COLLAPSE_THRESHOLD,
                        help="pages per section before its sidebar entry collapses")
    parser.add_argument("--force", action="store_true",
                        help="overwrite scaffold files the user has edited")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    site_title = args.site_title or root.name

    if args.action == "build":
        out = cmd_build(root, args.docs_dir, args.base_url, args.theme,
                        runner=args.runner, image_override=args.hugo_image)
    elif args.action == "image":
        out = {**resolve_image(root, args.hugo_image), "clean": True}
    elif args.action == "theme":
        out = cmd_theme(root / args.docs_dir, args.theme_ref, args.theme_url,
                        args.fetch, args.force)
    elif args.action == "mounts":
        docs = root / args.docs_dir
        out = ({"error": f"docs directory not found: {args.docs_dir}", "clean": False}
               if not docs.is_dir() else
               {"mounts": mounts_block(discover(docs, args.collapse_threshold),
                                       theme_state(docs, args.theme)["mode"] == "book"),
                "clean": True})
    else:
        out = run(root, args.docs_dir, site_title, args.description,
                  write=args.action == "scaffold", force=args.force,
                  theme_request=args.theme, threshold=args.collapse_threshold)

    json.dump(out, sys.stdout, ensure_ascii=False, indent=2)
    sys.stdout.write("\n")
    return 0 if out.get("clean", True) else 1


if __name__ == "__main__":
    sys.exit(main())
